### PR TITLE
Download data survey form

### LINKED ISSUE #167: add survey to download the data button
currently, the survey that users are prompted to take upon clicking "download" on the explore page is not working on the new site.

### PR DESCRIPTION
**Pull request by LayaTaal**
Adds a survey form modal that initiates once a user downloads a data set. The form stores a session variable so that it only opens the first time a user begins a download. A few notes:

1. The idea is to send this information to Google Analytics, which currently isn't hooked up. Once that is hooked up, we will need to come back and make sure this data gets sent where/how we want it.

2. I would prefer if we didn't need to open a new tab for mailchimp verification on the newsletter step, but in order to get this out a little quicker I am leaving it like this for now.

3. Incorporating the actual donation form into the modal would require reworking our PayPal implementation. For now, I decided to just redirect the user to the donation page and we can tackle this in a more elegant way after launching the site.

4. I'm still having trouble with the version of the `sharp` package we are using, and wasn't able to install `downloadjs` without updating `sharp` as well. 

Closes #167

### CODE REVIEW

File: components/SurveyModal.js [hunk 1]
```diff
@@ -0,0 +1,566 @@
...
+      <h2 className="tji-modal__title">Before you go...</h2>
+      <p className="tji-modal__description">
+        TJI provides its data to all users for free. Please consider making a contribution so we can continue to be a
+        free resource.
+      </p>
+      <div className="tji-modal__actions">
+        <button type="button" onClick={() => cancelForm()} className="btn--simple">
+          Not Now
+        </button>
+        <button type="button" className="btn btn--primary" onClick={() => (window.location.href = 'donate')}>
```
Comment (nholden) [inline components/SurveyModal.js]: When I clicked the "donate" button, I got a 404 because I was sent to `/data/donate`. I think this should fix it.

```suggestion
        <button type="button" className="btn btn--primary" onClick={() => (window.location.href = '/donate')}>
```

File: components/SurveyModal.js [hunk 2]
```diff
@@ -0,0 +1,566 @@
...
+    };
+
+    this.validateStep = this.validateStep.bind(this);
+    this.cancelForm = this.cancelForm.bind(this);
+    this.updateForm = this.updateForm.bind(this);
+    this.skipStep = this.skipStep.bind(this);
+  }
+
+  componentDidMount() {
+    const dataDownloaded = localStorage.getItem('dataDownloaded') === 'true';
```
Comment (nholden) [inline components/SurveyModal.js]: 👍👍 to the `localStorage` approach.

Do both `SurveyModal` and `DataDownloadButton` need to know about `dataDownloaded`? It might be nice if just one of them were responsible for deciding if we should render the modal.

File: components/SurveyModal.js [hunk 3]
```diff
@@ -0,0 +1,566 @@
...
+
+    this.setState({
+      formActive: !dataDownloaded,
+    });
+
+    localStorage.setItem('dataDownloaded', 'true');
+  }
+
+  // Validate required fields and either move to the next step or add an error message
+  validateStep(requiredFields = [], callback = () => {}) {
```
Comment (nholden) [inline components/SurveyModal.js]: I like this approach for validation!

One thing I've appreciated in form validation is when the form makes it clear specifically which fields are invalid. What do you think about incorporating that somehow? Do you think we could get any of that for cheap by leveraging HTML5 validation and the `required` attribute on the `<input>` elements?

File: components/SurveyModal.js [hunk 4]
```diff
@@ -0,0 +1,566 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import styled from 'styled-components';
+
+// Callback function for user to complete mailchimp signup
+function newsletterCallback() {
+  const mailchimpForm = document.getElementById('mailchimp-form');
+  mailchimpForm.action =
+    'https://texasjusticeinitiative.us18.list-manage.com/subscribe/post?u=fd262cb4a5fc0bafb38da2e22&amp;id=2663621fac';
```
Comment (nholden) [inline components/SurveyModal.js]: Should we stick our Mailchimp URL in a shared variable somewhere?

File: components/SurveyModal.js [hunk 5]
```diff
@@ -0,0 +1,566 @@
...
+  const { skipStep, validateStep, updateForm, stepError } = props;
+  const requiredFields = ['firstName', 'lastName', 'email'];
+  return (
+    <form
+      id="mailchimp-form"
+      name="mailchimp-form"
+      className="tji-modal__form"
+      // action="https://texasjusticeinitiative.us18.list-manage.com/subscribe/post?u=fd262cb4a5fc0bafb38da2e22&amp;id=2663621fac"
+      // method="post"
+      // target="_blank"
```
Comment (nholden) [inline components/SurveyModal.js]: Think we should be able to dump these commented lines.

File: components/SurveyModal.js [hunk 6]
```diff
@@ -0,0 +1,566 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import styled from 'styled-components';
+
+// Callback function for user to complete mailchimp signup
+function newsletterCallback() {
+  const mailchimpForm = document.getElementById('mailchimp-form');
```
Comment (nholden) [inline components/SurveyModal.js]: Is fetching an element by ID like this a smell? It feels like the "React way" to tie behavior to an element would be to use a component. Or if that doesn't work for some reason, a [`ref`](https://reactjs.org/docs/refs-and-the-dom.html).

File: components/SurveyModal.js (hunk 1 above)
Comment (nholden) [reply components/SurveyModal.js]: What do you think about opening the download page in a new tab? I'm thinking of the scenario where somebody sets up a bunch of specific filters and doesn't want to lose them.

Comment (LayaTaal) [reply components/SurveyModal.js]: I think you meant opening the donate page in a new tab. I like that idea, and implemented it in the latest update.

File: components/SurveyModal.js (hunk 2 above)
Comment (LayaTaal) [reply components/SurveyModal.js]: Agreed, I think just one of these can handle this. I've updated this.

File: components/SurveyModal.js (hunk 3 above)
Comment (LayaTaal) [reply components/SurveyModal.js]: I updated this to incorporate HTML5 validation as well. I agree, it's great to have both methods involved.

File: components/SurveyModal.js (hunk 4 above)
Comment (LayaTaal) [reply components/SurveyModal.js]: I think this is a good idea, but I'm not sure how we should go about this.

The two options that came to mind for me are to either use React's Context API, or Netlify's environment variables. Any thoughts?

File: components/SurveyModal.js (hunk 5 above)
Comment (LayaTaal) [reply components/SurveyModal.js]: Get out of here comments!

File: components/SurveyModal.js (hunk 6 above)
Comment (LayaTaal) [reply components/SurveyModal.js]: Agreed, I've updated this to use ref. I think we could probably rework our basic MailChimp component some to be more flexible, but I think I will save that for another time.

File: components/SurveyModal.js (hunk 1 above)
Comment (nholden) [reply components/SurveyModal.js]: > I think you meant opening the donate page in a new tab.

Whoops! Yep, totally.

Looks great! 👍

File: components/SurveyModal.js (hunk 2 above)
Comment (nholden) [reply components/SurveyModal.js]: Awesome work! 😍

File: components/SurveyModal.js (hunk 3 above)
Comment (nholden) [reply components/SurveyModal.js]: Nice! Looks great.

File: components/SurveyModal.js (hunk 4 above)
Comment (nholden) [reply components/SurveyModal.js]: Both of those options make sense to me. I think if this key were sensitive (i.e. a malicious user could find it on GitHub and do something bad with it) or if we wanted to use different keys in production and development, environment variables would be a clear winner. Since neither of those things are true right now, I'd be down with whichever approach you find easier to set up and maintain.

I'd be cool with merging this PR as-is and opening up a separate issue and PR to move this URL into a shared variable somewhere.

File: components/SurveyModal.js (hunk 6 above)
Comment (nholden) [reply components/SurveyModal.js]: Awesome! 👏
